FROM ubuntu:16.04
RUN apt-get update

RUN apt install -y software-properties-common git
RUN easy_install pip
RUN pip install git+git://github.com/ansible/ansible.git@devel
RUN ansible-galaxy install ontic.account
RUN ansible-galaxy install ontic.nodejs

COPY docker/initctl_faker .
RUN chmod +x initctl_faker && rm -fr /sbin/initctl && ln -s /initctl_faker /sbin/initctl
RUN echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts