# Copyright (c) Ontic. (http://www.ontic.com.au). All rights reserved.
# See the COPYING file bundled with this package for license details.

---

- name: 'Node.js | Include OS-specific variables.'
  include_vars: '{{ ansible_os_family }}.yml'
  tags:
    - 'nodejs'
    - 'nodejs-package'
    - 'package'

- name: 'Node.js | Include distribution-specific variables.'
  include_vars: 'RedHat-7.yml'
  when: 'ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"'
  tags:
    - 'nodejs'
    - 'nodejs-package'
    - 'package'

- name: 'Node.js | Define NPM user.'
  set_fact:
    nodejs_npm_global_user: '{{ ansible_user }}'
  when: 'not nodejs_npm_global_user'
  tags:
    - 'nodejs'
    - 'nodejs-package'
    - 'package'

- name: 'Node.js | Define NPM group.'
  set_fact:
    nodejs_npm_global_group: '{{ nodejs_npm_global_user }}'
  when: 'not nodejs_npm_global_group'
  tags:
    - 'nodejs'
    - 'nodejs-package'
    - 'package'

- include: 'package.yml'
  tags:
    - 'nodejs'
    - 'nodejs-package'
    - 'package'