# Copyright (c) Ontic. (http://www.ontic.com.au). All rights reserved.
# See the COPYING file bundled with this package for license details.

---

- name: 'Node.js | Debian | Install HTTPS transport.'
  become: yes
  apt:
    name: 'apt-transport-https'
    state: 'present'
  when: 'ansible_os_family == "Debian"'

- name: 'Node.js | Debian | Update repository key.'
  become: yes
  apt_key:
    id: '68576280'
    url: 'https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280'
    state: 'present'
  register: 'nodejs_key'
  when: 'ansible_os_family == "Debian"'

- name: 'Node.js | Debian | Update repository list.'
  become: yes
  apt_repository:
    repo: '{{ item }}'
    state: 'present'
  register: 'nodejs_list'
  with_items:
    - 'deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main'
    - 'deb-src https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main'
  when: 'ansible_os_family == "Debian"'

- name: 'Node.js | Debian | Update APT cache.'
  become: yes
  apt:
    update_cache: yes
  when: 'ansible_os_family == "Debian" and (nodejs_key.changed or nodejs_list.changed)'

- name: 'Node.js | Debian | Install Node.js.'
  become: yes
  apt:
    name: 'nodejs={{ nodejs_version|regex_replace("x", "") }}*'
    state: 'present'
  when: 'ansible_os_family == "Debian"'

- name: 'Node.js | RedHat | Import GPG keys.'
  become: yes
  rpm_key:
    key: '{{ nodejs_rpm_key }}'
    state: 'present'
  when: 'ansible_os_family == "RedHat"'

- name: 'Node.js | RedHat | Install Node.js source repository.'
  become: yes
  yum:
    name: '{{ nodejs_rpm_url }}'
    state: 'present'
  when: 'ansible_os_family == "RedHat"'

- name: 'Node.js | RedHat | Install Node.js.'
  become: yes
  yum:
    name: 'nodejs-{{ nodejs_version[0] }}.*'
    enablerepo: 'epel,nodesource'
    state: 'present'
  when: 'ansible_os_family == "RedHat"'

- name: 'Node.js | Ensure the NPM global directory exists.'
  become: yes
  file:
    path: '{{ nodejs_npm_global_config_prefix }}'
    state: 'directory'
    owner: '{{ nodejs_npm_global_user }}'
    group: '{{ nodejs_npm_global_group }}'
    mode: '0755'

- name: 'Node.js | Configure global PATH environment variable.'
  become: yes
  template:
    src: 'npm.sh.j2'
    dest: '/etc/profile.d/npm.sh'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: 'Node.js | Debian | Install Node.js packages.'
  become: yes
  apt:
    name: '{{ item.name if item.version is not defined else item.name + "=" + item.version }}'
    cache_valid_time: '{{ item.cache_valid_time | default(omit) }}'
    deb: '{{ item.deb | default(omit) }}'
    default_release: '{{ item.default_release | default(omit) }}'
    dpkg_options: '{{ item.dpkg_options | default(omit) }}'
    force: '{{ item.force | default(omit) }}'
    install_recommends: '{{ item.install_recommends | default(omit) }}'
    purge: '{{ item.purge | default(omit) }}'
    state: '{{ item.state | default(omit) }}'
    update_cache: '{{ item.update_cache | default(omit) }}'
    upgrade: '{{ item.upgrade | default(omit) }}'
  with_items: '{{ nodejs_packages }}'
  when: 'nodejs_packages and ansible_os_family == "Debian"'

- name: 'Node.js | RedHat | Install Node.js packages.'
  become: yes
  yum:
    name: '{{ item.name if item.version is not defined else item.name + "-" + item.version }}'
    conf_file: '{{ item.conf_file | default(omit) }}'
    disable_gpg_check: '{{ item.disable_gpg_check | default(omit) }}'
    disablerepo: '{{ item.disablerepo | default(omit) }}'
    enablerepo: '{{ item.enablerepo | default(omit) }}'
    exclude: '{{ item.exclude | default(omit) }}'
    list: '{{ item.list | default(omit) }}'
    state: '{{ item.state | default(omit) }}'
    update_cache: '{{ item.update_cache | default(omit) }}'
  with_items: '{{ nodejs_packages }}'
  when: 'nodejs_packages and ansible_os_family == "RedHat"'

# TODO: Remove this task after Ansible 2.x npm module bug is fixed. See:
# https://github.com/ansible/ansible-modules-extras/issues/1375
- name: 'Node.js | Ensure NPM global packages are installed.'
  become: yes
  npm:
    name: '{{ item.name }}'
    version: '{{ item.version | default("latest") }}'
    executable: '{{ item.executable | default(omit) }}'
    ignore_scripts: '{{ item.ignore_scripts | default(omit) }}'
    path: '{{ item.path | default(omit) }}'
    production: '{{ item.production | default(omit) }}'
    registry: '{{ item.registry | default(omit) }}'
    state: '{{ item.state | default(omit) }}'
    global: yes
  environment:
    NPM_CONFIG_PREFIX: '{{ nodejs_npm_global_config_prefix }}'
    NODE_PATH: '{{ nodejs_npm_global_config_prefix }}/lib/node_modules'
    NPM_CONFIG_UNSAFE_PERM: '{{ nodejs_npm_global_config_unsafe_perm }}'
  with_items: '{{ nodejs_npm_global_packages }}'
  when: 'nodejs_npm_global_packages'

- name: 'Node.js | Ensure NPM global packages are the latest release.'
  become: yes
  npm:
    name: '{{ item.name }}'
    version: '{{ item.version | default("latest") }}'
    executable: '{{ item.executable | default(omit) }}'
    ignore_scripts: '{{ item.ignore_scripts | default(omit) }}'
    path: '{{ item.path | default(omit) }}'
    production: '{{ item.production | default(omit) }}'
    registry: '{{ item.registry | default(omit) }}'
    state: 'latest'
    global: yes
  environment:
    NPM_CONFIG_PREFIX: '{{ nodejs_npm_global_config_prefix }}'
    NODE_PATH: '{{ nodejs_npm_global_config_prefix }}/lib/node_modules'
    NPM_CONFIG_UNSAFE_PERM: '{{ nodejs_npm_global_config_unsafe_perm }}'
  with_items: '{{ nodejs_npm_global_packages }}'
  when: 'nodejs_npm_global_packages and item.state | default("present") != "absent"'

- name: 'Node.js | Install NPM packages.'
  become: yes
  become_user: '{{ item.user }}'
  npm:
    name: '{{ item.name }}'
    version: '{{ item.version | default("latest") }}'
    executable: '{{ item.executable | default(omit) }}'
    ignore_scripts: '{{ item.ignore_scripts | default(omit) }}'
    path: '{{ item.path | default(omit) }}'
    production: '{{ item.production | default(omit) }}'
    registry: '{{ item.registry | default(omit) }}'
    state: '{{ item.state | default(omit) }}'
    global: '{{ item.global | default(omit) }}'
  with_items: '{{ nodejs_npm_packages }}'
  when: 'nodejs_npm_packages and item.user is defined'